[project]
name = "customer-support-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rajgurubhosale", email = "bhosalerajguru007@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "faker>=40.37.0",
    "langchain-core>=1.6.0",
    "langgraph>=1.2.11",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
]

[project.scripts]
customer-support-ai-agent = "customer_support_ai_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
