from pydantic import BaseModel, Field
from typing import Optional, List, Any, Dict


class ChatRequest(BaseModel):
    user_id: int = Field(..., description="Customer ID (e.g. 29)")
    message: Optional[str] = Field(
        default=None,
        description="Customer input text. If null/empty on a new thread, the API starts the graph and returns the initial greeting.",
    )
    thread_id: Optional[str] = Field(
        default=None,
        description="Unique conversation session ID. If omitted, defaults to 'user-{user_id}'.",
    )


class ChatResponse(BaseModel):
    thread_id: str
    user_id: int
    status: str = Field(
        ...,
        description="Session state: 'waiting_for_input' (interrupted/awaiting reply) or 'completed' (session ended).",
    )
    ai_response: str = Field(
        ...,
        description="The primary prompt or message to display to the user in the chat window.",
    )
    messages: List[str] = Field(
        default_factory=list,
        description="Any intermediate status or receipt messages generated by graph nodes.",
    )
    current_action: Optional[str] = Field(
        default=None,
        description="Current workflow action (e.g. 'cancel_order', 'return_order', 'exit').",
    )
    order_id: Optional[str] = Field(
        default=None,
        description="Active order ID being processed, if any.",
    )
